/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/camera.glb --transform 
Files: public/camera.glb [2.07MB] > /Users/abisheks/cctv-site/camera-transformed.glb [221.52KB] (89%)
Author: Vladyslav Holhanov (https://sketchfab.com/vladicom08)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/security-camera-03aa77b6c6864f3e93fc3deecbd79309
Title: Security Camera
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/camera-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere002__0.geometry} material={materials['Scene_-_Root']} position={[0, 0.966, -0.008]} rotation={[-0.798, 0, 0]} scale={0.891} />
    </group>
  )
}

useGLTF.preload('/camera-transformed.glb')
